SET NAMES utf8mb4;

CREATE TABLE roles (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL UNIQUE, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL) ENGINE=InnoDB;
CREATE TABLE permissions (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, slug VARCHAR(120) NOT NULL UNIQUE, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL) ENGINE=InnoDB;
CREATE TABLE offices (id INT AUTO_INCREMENT PRIMARY KEY, parent_id INT NULL, name VARCHAR(150) NOT NULL, address VARCHAR(255), notes TEXT, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, CONSTRAINT fk_offices_parent FOREIGN KEY (parent_id) REFERENCES offices(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE employees (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL, employee_number VARCHAR(80), designation VARCHAR(150), department VARCHAR(150), office_id INT NULL, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, FOREIGN KEY (office_id) REFERENCES offices(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL, username VARCHAR(80) NOT NULL UNIQUE, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role_id INT NOT NULL, office_id INT NULL, status VARCHAR(20) NOT NULL DEFAULT 'active', last_login_at TIMESTAMP NULL, last_seen_at TIMESTAMP NULL, logged_out_at TIMESTAMP NULL, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT, FOREIGN KEY (office_id) REFERENCES offices(id) ON DELETE SET NULL, CHECK (status IN ('active','disabled'))) ENGINE=InnoDB;
CREATE TABLE role_permissions (role_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY (role_id, permission_id), FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE, FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE computers (id BIGINT AUTO_INCREMENT PRIMARY KEY, computer_name VARCHAR(150) NOT NULL UNIQUE, device_name VARCHAR(150), device_type VARCHAR(80) NOT NULL DEFAULT 'Computer', mac_address VARCHAR(40), notes TEXT, added_by_user_id INT NULL, is_offline_device SMALLINT NOT NULL DEFAULT 0, manufacturer VARCHAR(150), model VARCHAR(150), serial_number VARCHAR(150), firmware_version VARCHAR(150), domain_workgroup VARCHAR(150), os_name VARCHAR(190), os_version VARCHAR(190), build_number VARCHAR(80), cpu_name VARCHAR(190), battery_health_percent SMALLINT, ram_bytes BIGINT, disk_summary JSON, motherboard VARCHAR(190), office_id INT NULL, assigned_employee_id INT NULL, agent_version VARCHAR(80), agent_token_hash CHAR(64), agent_uninstalled_at TIMESTAMP NULL, last_checkin_at TIMESTAMP NULL, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, FOREIGN KEY (added_by_user_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY (office_id) REFERENCES offices(id) ON DELETE SET NULL, FOREIGN KEY (assigned_employee_id) REFERENCES employees(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE agent_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY, computer_id BIGINT NULL, level VARCHAR(20) NOT NULL, message VARCHAR(1000) NOT NULL, context JSON, created_at TIMESTAMP NOT NULL, FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE agent_events (id BIGINT AUTO_INCREMENT PRIMARY KEY, event_id VARCHAR(120) NOT NULL UNIQUE, computer_id BIGINT NOT NULL, event_type VARCHAR(80) NOT NULL, payload_hash CHAR(64) NOT NULL, observed_at TIMESTAMP NULL, processed_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE audit_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id INT NULL, action VARCHAR(80) NOT NULL, entity_type VARCHAR(120) NOT NULL, entity_id BIGINT NULL, metadata JSON, ip_address VARCHAR(80), created_at TIMESTAMP NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE bios_information (id BIGINT AUTO_INCREMENT PRIMARY KEY, computer_id BIGINT NOT NULL UNIQUE, manufacturer VARCHAR(150), version VARCHAR(190), release_date DATE, update_date DATE, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE device_maintenance_history (id BIGINT AUTO_INCREMENT PRIMARY KEY, computer_id BIGINT NOT NULL, field_name VARCHAR(80) NOT NULL, display_name VARCHAR(120) NOT NULL, previous_value TEXT, current_value TEXT, changed_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE device_maintenance_hidden_records (maintenance_id BIGINT NOT NULL, user_id INT NOT NULL, created_at TIMESTAMP NOT NULL, PRIMARY KEY (maintenance_id, user_id), FOREIGN KEY (maintenance_id) REFERENCES device_maintenance_history(id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE installed_software (id BIGINT AUTO_INCREMENT PRIMARY KEY, computer_id BIGINT NOT NULL, name VARCHAR(255) NOT NULL, version VARCHAR(120), publisher VARCHAR(190), installed_date DATE, last_updated_date DATE, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE installed_drivers (id BIGINT AUTO_INCREMENT PRIMARY KEY, computer_id BIGINT NOT NULL, device_name VARCHAR(255) NOT NULL, version VARCHAR(120), provider VARCHAR(190), manufacturer VARCHAR(190), driver_date DATE, installed_date DATE, last_updated_date DATE, inf_name VARCHAR(190), device_class VARCHAR(120), created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE driver_history (id BIGINT AUTO_INCREMENT PRIMARY KEY, computer_id BIGINT NOT NULL, device_name VARCHAR(255) NOT NULL, previous_version VARCHAR(120), current_version VARCHAR(120), change_type VARCHAR(20) NOT NULL, created_at TIMESTAMP NOT NULL, FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE CASCADE, CHECK (change_type IN ('installed','updated','removed'))) ENGINE=InnoDB;
CREATE TABLE locations (id INT AUTO_INCREMENT PRIMARY KEY, office_id INT NOT NULL, name VARCHAR(150) NOT NULL, address VARCHAR(255), created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, FOREIGN KEY (office_id) REFERENCES offices(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE login_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id INT NULL, email VARCHAR(190), ip_address VARCHAR(80), user_agent VARCHAR(255), success SMALLINT NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE network_information (id BIGINT AUTO_INCREMENT PRIMARY KEY, computer_id BIGINT NOT NULL, adapter_name VARCHAR(190), adapter_type VARCHAR(20) NOT NULL DEFAULT 'Other', mac_address VARCHAR(40), ip_addresses JSON, hostname VARCHAR(150), created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE software_history (id BIGINT AUTO_INCREMENT PRIMARY KEY, computer_id BIGINT NOT NULL, software_name VARCHAR(255) NOT NULL, previous_version VARCHAR(120), current_version VARCHAR(120), change_type VARCHAR(20) NOT NULL, created_at TIMESTAMP NOT NULL, FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE CASCADE, CHECK (change_type IN ('installed','updated','removed'))) ENGINE=InnoDB;
CREATE TABLE software_sync_requests (id BIGINT AUTO_INCREMENT PRIMARY KEY, computer_id BIGINT NOT NULL, requested_by_user_id INT NULL, requested_at TIMESTAMP NOT NULL, completed_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE CASCADE, FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE driver_sync_requests (id BIGINT AUTO_INCREMENT PRIMARY KEY, computer_id BIGINT NOT NULL, requested_by_user_id INT NULL, requested_at TIMESTAMP NOT NULL, completed_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE CASCADE, FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE update_assignments (id BIGINT AUTO_INCREMENT PRIMARY KEY, assignment_group_key VARCHAR(40), computer_id BIGINT NOT NULL, task_kind VARCHAR(20) NOT NULL, task_type VARCHAR(80), software_name VARCHAR(255), assigned_to_user_id INT NOT NULL, assigned_by_user_id INT NULL, note TEXT, status VARCHAR(20) NOT NULL DEFAULT 'pending', completed_at TIMESTAMP NULL, evidence_type VARCHAR(40), evidence_id BIGINT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, FOREIGN KEY (computer_id) REFERENCES computers(id) ON DELETE CASCADE, FOREIGN KEY (assigned_to_user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (assigned_by_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE app_settings (id BIGINT AUTO_INCREMENT PRIMARY KEY, setting_key VARCHAR(120) NOT NULL UNIQUE, setting_value TEXT NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL) ENGINE=InnoDB;

CREATE INDEX idx_computer_serial ON computers(serial_number); CREATE INDEX idx_computer_checkin ON computers(last_checkin_at); CREATE INDEX idx_agent_logs_computer ON agent_logs(computer_id); CREATE INDEX idx_audit_created ON audit_logs(created_at); CREATE INDEX idx_software_computer ON installed_software(computer_id); CREATE INDEX idx_driver_computer ON installed_drivers(computer_id); CREATE INDEX idx_users_last_seen ON users(last_seen_at); CREATE INDEX idx_offices_parent ON offices(parent_id);

INSERT INTO roles (id,name,slug,created_at,updated_at) VALUES (1,'Super Admin','super-admin',NOW(),NOW()),(2,'Admin','admin',NOW(),NOW()),(3,'User','user',NOW(),NOW());
INSERT INTO permissions (id,name,slug,created_at,updated_at) VALUES (1,'View Devices','assets.view',NOW(),NOW()),(2,'Manage Devices','assets.manage',NOW(),NOW()),(3,'Manage Users','users.manage',NOW(),NOW()),(4,'Manage Offices','offices.manage',NOW(),NOW()),(5,'View Reports','reports.view',NOW(),NOW()),(6,'Export Reports','reports.export',NOW(),NOW()),(7,'View Audit Logs','audit.view',NOW(),NOW()),(8,'Manage Employees','employees.manage',NOW(),NOW());
INSERT INTO role_permissions SELECT 1,id FROM permissions; INSERT INTO role_permissions SELECT 2,id FROM permissions WHERE slug IN ('assets.view','assets.manage','users.manage','offices.manage','employees.manage','reports.view','reports.export'); INSERT INTO role_permissions SELECT 3,id FROM permissions WHERE slug IN ('assets.view','assets.manage','offices.manage','employees.manage','reports.view','reports.export');
INSERT INTO offices (id,name,created_at,updated_at) VALUES (1,'Main Office',NOW(),NOW());
INSERT INTO users (id,name,username,email,password_hash,role_id,office_id,status,created_at,updated_at) VALUES (1,'System Administrator','admin','admin@example.com','$2y$12$g040GPUYh9NdSQWGBbuo5uaaf4XaGsUyyBCSOKymudSyKQ7H0gfjS',1,1,'active',NOW(),NOW());
